Iot_ML_Kit/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "website"

urlpatterns = [
	path('', views.index, name='index'),
	path('form/', views.input_form, name='form'),
	# path('opt/event/', views.uploadEvents, name='opt-event'),
	# path('opt/announcement/', views.uploadAnn, name='opt-announcement'),
	# path('opt/placement/', views.uploadPlacement, name='opt-placement'),
	# path('', views.indexpage, name='index'),
	# path('login/', views.LoginFormView, name='index'),
	# path('announcement/', views.announcement, name='announcement'),
	# path('opt/announcement/', views.announcement, name='opt-announcement'),
	# path('event/', views.event, name='event'),
	# path('opt/event/', views.event, name='opt-event'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse


#ML models imports
import pandas as pd
import numpy as np

import datetime
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

import datetime

# Create your views here.
def index(request):
	if request.method == "GET":
		return render(request, 'index.html')


def input_form(request):
	if request.method=="GET":
		return render(request, 'form.html')
	elif request.method=="POST":
		channel_id = request.POST.get('channel_id')
		field_no = request.POST.get('field_number')
		model = request.POST.get('model')
		print('[+]Thingspeak Credentials: ', channel_id,field_no,model)

		url_thingspeak = 'https://thingspeak.com/channels/'+channel_id+'/fields/'+field_no+'.csv'
		request.session['website'] = 'IOT_ML_KIT'
		#print('[+]SessionKey: '+request.session.session_key)

		#filename = model+"_"+str(request.session.session_key)+'.png'
		filename = model+"_"+str(datetime.datetime.now().timestamp())+'.png'
		if model=="LR":
			linearmodel(url_thingspeak, 'static/images/'+filename)
		elif model=="SV":
			supportvector(url_thingspeak, 'static/images/'+filename)
		elif model=="RF":
			randomforest(url_thingspeak, 'static/images/'+filename)

		return render(request, 'data_visualize.html', {'filename':filename})

def data_preprocess(url):
	data = pd.read_csv(url)

	# Preprocessing string to timestamp
	#2019-06-03 10:47:42 UTC
	for i in range(len(data['created_at'])):
	    dt = datetime.datetime.strptime(data['created_at'][i], '%Y-%m-%d %H:%M:%S UTC')
	    data['created_at'][i] = dt.timestamp()

	#  (X, Y) - (Timestamp, Temperature)
	X = data['created_at'].to_numpy().reshape(-1,1)
	y = data['field1'].to_numpy().reshape(-1,1)

	return X,y

def supportvector(url, filename):
	X,y = data_preprocess(url)

	# Fitting SVR to the dataset
	from sklearn.svm import SVR
	regressor_svr = SVR(kernel = 'rbf')
	regressor_svr.fit(X, y)

	# Visualising the SVR results (for higher resolution and smoother curve)
	import matplotlib.pyplot as pltsv
	pltsv.scatter(X, y, color = 'red')
	pltsv.plot(X, regressor_svr.predict(X), color = 'blue')
	pltsv.title('Support Vector')
	pltsv.xlabel('Timestamp')
	pltsv.ylabel('Temperature')
	#plt.show()
	pltsv.savefig(filename)
	print('[+]Image Saved')
	

def randomforest(url, filename):
	X,y = data_preprocess(url)

	# Fitting Random Forest Regression to the dataset
	regressor_rf = RandomForestRegressor(n_estimators = 10000, random_state = 0)
	regressor_rf.fit(X, y)

	# Visualising the SVR results (for higher resolution and smoother curve)
	import matplotlib.pyplot as plt
	plt.scatter(X, y, color = 'red')
	plt.plot(X, regressor_rf.predict(X), color = 'blue')
	plt.title('Random Forest')
	plt.xlabel('Timestamp')
	plt.ylabel('Temperature')
	#plt.show()
	plt.savefig(filename)
	print('[+]Image Saved')


def linearmodel(url, filename):
	X,y = data_preprocess(url)

	# Splitting Data into Training & Testing
	# TODO Split in 80:20, i.e. 10 for test and 20 for training
	X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

	# WELL DONE! YOUR DATA IS PREPROCESSED

	# Fitting SIMPLE LINEAR REGRESSION to the Training Set
	from sklearn.linear_model import LinearRegression
	regressor_lr = LinearRegression()
	regressor_lr.fit(X_train, y_train)

	# Visualising the Training set results
	import matplotlib.pyplot as pltlm
	pltlm.scatter(X_train, y_train, color='red', label='predicted')
	pltlm.plot(X_train, regressor_lr.predict(X_train), color='blue', label='actual')
	pltlm.title('Linear Regression')
	pltlm.xlabel('Timestamp')
	pltlm.ylabel('Temperature')
	pltlm.legend(loc='upper left', numpoints=1)
	#plt.show()
	pltlm.savefig(filename)
	print('[+]Image Saved')

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
	<style>
	.center {
		display: block;
		margin-left: auto;
		margin-right: auto;
		width: 50%;
	}
	/* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    .card{
        margin: 0 auto;
        float: none;
        margin-bottom: 10px;
        margin-top: 100px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
	</style>
</head>
<body>
        <nav class="navbar navbar-inverse">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                  </button>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav">
                    <li class="active"><a href="/">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                  </ul>
                </div>
              </nav>  
{% block content %}{% endblock %} 
</body>
</html>

website/templates/data_visualize.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<img class="center" src="{% static 'images/' %}{{ filename }}">
{% endblock %}

website/templates/form.html
{% extends 'base.html' %}
{% block title %}FORM | ThingSpeak{% endblock %}
{% block content %}
    <div class="container">
    <form action="{% url 'website:form' %}" method="POST">
      {% csrf_token %}
        <div class="row justify-content-md-center" style="display: flex;justify-content:center;margin-top:100px;">
            <div class="col-md-4">
              <h2 style="text-align:center">ThingSpeak</h2><bR>
                    <div class="form-group">
                        <label for="email">Channel ID:</label>
                        <input type="number" class="form-control" name="channel_id">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Field Number :</label>
                        <input type="number" class="form-control" name="field_number">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Model :</label>
                        <select class="form-control"  name="model">
                          <option value="LR">Linear Regression Model</option>
                          <option value="SV">Support Vector</option>
                          <option value="RF">Random Forest</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
    </div>
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}

{% block title %}HOME | IOTMLKIT{% endblock %}

{% block content %}

  <div class="container-fluid">
      <div class="row justify-content-md-center content-align-center" style="display: flex;justify-content:center;">
        <div class="col">
            Welcome to our website Click <a href="{% url 'website:form' %}">here</a> to get started
        </div>
      </div>
  </div>
{% endblock %}